[hardened_nodes]
localhost ansible_connection=local

# --- Production Enterprise Servers (Remote IP Addresses) ---
#192.168.1.50 ansible_user=admin_user ansible_ssh_private_key_file=~/.ssh/client_key
#192.168.1.60 ansible_user=deploy_user ansible_ssh_private_key_file=~/.ssh/client_key
#10.0.0.15   ansible_user=root_user   ansible_ssh_private_key_file=~/.ssh/id_rsa

