---
- name: "RECOVERY | Bypass Interactive PAM Gates"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # ⚠️ TYPE YOUR DIFFERENT PASSWORDS HERE:
    new_vega_password: "Honduras504!!"
    new_root_password: "Marina0119!!"

  tasks:
    - name: "RECOVERY | Force write pristine 65536-round hashes straight to disk file"
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pwd | password_hash('sha512', rounds=65536) }}"
        update_password: always
      loop:
        - { name: 'vega', pwd: "{{ new_vega_password }}" }
        - { name: 'root', pwd: "{{ new_root_password }}" }

